gazebo_ros_control:
  pid_gains:
    base_link_to_fork_left_horizontal:
      p: 2000.0
      i: 0.01
      d: 10.0
      i_clamp: 1.0
    fork_left_horizontal_to_fork_left_vertical:
      p: 2000.0
      i: 0.01
      d: 10.0
      i_clamp: 1.0
    base_link_to_fork_right_horizontal:
      p: 2000.0
      i: 0.01
      d: 10.0
      i_clamp: 1.0
    fork_right_horizontal_to_fork_right_vertical:
      p: 2000.0
      i: 0.01
      d: 10.0
      i_clamp: 1.0


base_link_to_fork_left_horizontal_controller:
  type: position_controllers/JointPositionController
  joint: base_link_to_fork_left_horizontal
  pid: {p: 2000.0, i: 0.01, d: 10.0}

fork_left_horizontal_to_fork_left_vertical_controller:
  type: position_controllers/JointPositionController
  joint: fork_left_horizontal_to_fork_left_vertical
  pid: {p: 2000.0, i: 0.01, d: 10.0}

base_link_to_fork_right_horizontal_controller:
  type: position_controllers/JointPositionController
  joint: base_link_to_fork_right_horizontal
  pid: {p: 2000.0, i: 0.01, d: 10.0}

fork_right_horizontal_to_fork_right_vertical_controller:
  type: position_controllers/JointPositionController
  joint: fork_right_horizontal_to_fork_right_vertical
  pid: {p: 2000.0, i: 0.01, d: 10.0}