fork_controller:
  type: "effort_controllers/JointPositionController"
  joint: "base_to_fork"
  pid: {p: 3000.0, i: 0.5, d: 0.5}

# 添加其他关节的PID增益
front_left_wheel_controller:
  type: "effort_controllers/JointVelocityController"
  joint: "front_left_wheel"
  pid: {p: 100.0, i: 0.0, d: 0.0}

front_right_wheel_controller:
  type: "effort_controllers/JointVelocityController"
  joint: "front_right_wheel"
  pid: {p: 100.0, i: 0.0, d: 0.0}

rear_left_wheel_controller:
  type: "effort_controllers/JointVelocityController"
  joint: "rear_left_wheel"
  pid: {p: 100.0, i: 0.0, d: 0.0}

rear_right_wheel_controller:
  type: "effort_controllers/JointVelocityController"
  joint: "rear_right_wheel"
  pid: {p: 100.0, i: 0.0, d: 0.0}